// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`                         // 用户ID
	OrganizationID string `gorm:"column:organization_id;not null" json:"organization_id"` // 机构ID
	ApplicationID  string `gorm:"column:application_id;not null" json:"application_id"`   // 应用ID
	Mobile         string `gorm:"column:mobile;not null" json:"mobile"`                   // 手机号
	Name           string `gorm:"column:name;not null" json:"name"`                       // 姓名
	IsDeleted      bool   `gorm:"column:is_deleted;not null" json:"is_deleted"`           // 删除状态:0-未删除,1-已删除
	CreatedOn      int32  `gorm:"column:created_on;not null" json:"created_on"`           // 创建时间(UNIX时间戳)
	UpdatedOn      int32  `gorm:"column:updated_on;not null" json:"updated_on"`           // 更新时间(UNIX时间戳)
	DeletedOn      int32  `gorm:"column:deleted_on;not null" json:"deleted_on"`           // 删除时间(UNIX时间戳)
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
